### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by Schmavery** [bsansouci/reasongl#2]
We're having trouble linking opengl properly on linux. Needs to be fixed.

**Comment by Schmavery** [comment]
This is basically done, but audio is tricky on linux so we want to tweak the audio support so that it prints a warning rather than crashing if an audio device can't be found.

**Comment by zploskey** [comment]
I think this can be closed now. No more Linux build issues.

**Comment by Schmavery** [comment]
There's one other related issue that comes to mind:
https://github.com/bsansouci/reprocessing-example/issues/7
https://github.com/bsansouci/reprocessing-example/issues/8

The fix is either to remove -lasound like in  your fix https://github.com/bsansouci/SDL-mirror/pull/2 if that works or (if we have to) add a note to the README, I guess.

**Comment by Schmavery** [comment]
Closing as I believe there are no outstanding linux support issues, aside for https://github.com/Schmavery/reprocessing/issues/76 maybe
